### PR TITLE
Add MIT + Apache-2.0 dual license

### PR DESCRIPTION
**Pull request by nicholastmosher**
I didn't know anything about licensing when I created this project, but since others are finding it useful I'd like to add the MIT + Apache-2.0 dual license to the project.

@per1234, @Dzitu, @CodingGhost, you have each merged code to this repo, so could you please reply in a comment saying you agree for your contributions to also be MIT + Apache-2.0 dual-licensed? Something along the following lines:

> I agree for my contributions to be dual-licensed under MIT + Apache-2.0.

This is standard for an open-source project, and just means that you are explicitly allowing others to use this project and the code you've added to it freely. Thanks!

## Pending responses:

- [x] @per1234 
- [x] @Dzitu 
- [x] @CodingGhost

### CODE REVIEW

**Review by CodingGhost — APPROVED** [review]

**Comment by CodingGhost** [comment]
sorry, completely overread the middle part and just clicked merge. damn this was dumb, was the first time I used a repo ,that was not mine, in the web gui that I had merge rights.

I agree for my contributions to be dual-licensed under MIT + Apache-2.0.

**Comment by Dzitu** [comment]
I agree for my contributions to be dual-licensed under MIT + Apache-2.0.

**Comment by nicholastmosher** [comment]
@CodingGhost no worries, I went and double-checked and @per1234 only touched the `keywords.txt`, which does not have any bearing on the behavior of the library, only syntax highlighting in Arduino IDE. I think we should be fine to leave this and if they're around they can reply to this if they wish ❤️

**Comment by per1234** [comment]
I agree for my contributions to be dual-licensed under MIT + Apache-2.0.

I also relinquish any copyright claim I might have on my trivial contribution so you are free to make any future changes to the licensing of the library without first obtaining my permission.

**Pull request merged**
